name: Deploy Project
on: push
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Get Code
              uses: actions/checkout@v6
            - name: Install Nodde JS
              uses: actions/setup-node@v4
              with:
                node-version: 19
            - name: Install dependencies
              run: nmp ci
            - name: Run Test
              run: nmp test
    deploy:
        needs: test
        runs-on: ubuntu-latest
        steps:
            - name: Get Code
              uses: actions/checkout@v6
            - name: Install Nodde JS
              uses: actions/setup-node@v4
              with:
                node-version: 19
            - name: Install dependencies
              run: nmp ci
            - name: Build Project
              run: nmp run build
            - name: Deploy
              run: echo "Deploying ..."
            